/*
 * This source file was generated by the Gradle 'init' task
 */
package tugaspbo;

public class App {
    public static void main(String[] args) {
        System.out.println("=== Aplikasi Sistem Mahasiswa ===");
        tugaspbo.database.JoptionPaneDatabase.Menu();
    }
}

